apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace : devacm3
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: acm-test-pod2
  namespace : devacm3
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: acm-test-container

